[package]
name = "kaal-compose"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "kaal-compose"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive", "cargo"] }
thiserror.workspace = true
serde.workspace = true
toml = "0.8"
anyhow = "1.0"
colored = "2.0"

[dev-dependencies]
