[package]
name = "kaal-root-task"
version = "0.1.0"
edition = "2021"

[dependencies]
sel4-platform = { path = "../sel4-platform" }
cap-broker = { path = "../cap_broker" }

[features]
default = ["runtime"]
runtime = []
