[package]
name = "test-minimal"
version = "0.1.0"
edition = "2021"

# Empty workspace table to prevent this from being part of parent workspace
[workspace]

[dependencies]
# No dependencies - bare metal

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true