[package]
name = "sel4-mock"
version = "0.1.0"
edition = "2021"
authors = ["KaaL Team"]
license = "MIT OR Apache-2.0"

[dependencies]
sel4-mock-sys = { path = "../sel4-mock" }

[package.metadata.docs.rs]
default-target = "x86_64-unknown-none"
