[package]
name = "kernel-test"
version = "0.1.0"
edition = "2021"

[dependencies]
kaal-kernel = { path = "../../kernel", features = ["testing"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
