[package]
name = "sel4-mock-sys"
version = "0.1.0"
edition = "2021"
authors = ["KaaL Team"]
license = "MIT OR Apache-2.0"

[lib]
name = "sel4_mock_sys"

[package.metadata.docs.rs]
default-target = "x86_64-unknown-none"
