[package]
name = "kaal-posix"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
log.workspace = true

# Internal dependencies
kaal-vfs = { path = "../vfs" }
kaal-ipc = { path = "../../runtime/ipc" }

[dev-dependencies]
