[package]
name = "notepad"
version = "0.1.0"
edition = "2021"

[workspace]
# Opt out of parent workspace

[dependencies]
kaal-sdk = { path = "../../sdk/kaal-sdk" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
