[package]
name = "kaal-vfs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
log.workspace = true

# Internal dependencies
kaal-ipc = { path = "../../runtime/ipc" }

[dev-dependencies]
criterion.workspace = true
