[package]
name = "dummy-roottask"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "dummy-roottask"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
