name: Formal Verification

on:
  push:
    branches: [ main ]
    paths:
      - 'kernel/src/verified/**'
      - 'scripts/verify.nu'
      - '.github/workflows/verification.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'kernel/src/verified/**'
      - 'scripts/verify.nu'
      - '.github/workflows/verification.yml'
  workflow_dispatch:

jobs:
  verify:
    name: Verus Verification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.88.0

      - name: Install Nushell
        run: |
          wget https://github.com/nushell/nushell/releases/download/0.98.0/nu-0.98.0-x86_64-unknown-linux-gnu.tar.gz
          tar xzf nu-0.98.0-x86_64-unknown-linux-gnu.tar.gz
          sudo mv nu-0.98.0-x86_64-unknown-linux-gnu/nu /usr/local/bin/
          nu --version

      - name: Cache Verus
        id: cache-verus
        uses: actions/cache@v4
        with:
          path: ~/verus
          key: verus-latest-${{ runner.os }}

      - name: Install Verus
        if: steps.cache-verus.outputs.cache-hit != 'true'
        run: |
          # Download latest release to temp location
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/verus-lang/verus/releases/latest | grep "browser_download_url.*x86-linux.zip" | cut -d '"' -f 4)
          wget -O /tmp/verus.zip "$DOWNLOAD_URL"

          # Extract to temp and move to final location
          unzip -q /tmp/verus.zip -d /tmp/verus-extract

          # Find the extracted directory and move all contents (including hidden files)
          EXTRACTED_DIR=$(find /tmp/verus-extract -mindepth 1 -maxdepth 1 -type d | head -n 1)
          mkdir -p ~/verus
          mv "$EXTRACTED_DIR"/* ~/verus/
          mv "$EXTRACTED_DIR"/.[!.]* ~/verus/ 2>/dev/null || true

          chmod +x ~/verus/verus
          ~/verus/verus --version

      - name: Run Verus verification
        run: |
          export PATH="$HOME/verus:$PATH"
          nu scripts/verify.nu 2>&1 | tee /tmp/verify.log

      - name: Summary
        if: success()
        run: |
          echo "✅ Verification completed successfully!"
          echo "All 6 modules verified, 0 errors"
